import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start gap-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] p-8">
        <nav className="flex w-96 flex-row justify-center gap-8 p-2 tracking-wider text-white">
          <Link href="/">About</Link>
          <Link href="/">Projects</Link>
        </nav>
        <div className="flex h-96 w-96 flex-col items-center justify-center rounded-lg border-4 bg-white bg-opacity-25 p-2 text-center tracking-widest text-white">
          <p>Welcome</p>
          <p>Hallo, this is Seany Beany website</p>
          <p>Do you love Seany Beany</p>
          <p>I sure do</p>
        </div>
      </main>
    </>
  );
};

export default Home;
